version: "3.9"

services:
  ml-service:
    build: ./ml-service
    container_name: finiq-ml
    ports:
      - "5001:5001"
    env_file:
      - ./ml-service/.env
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: finiq-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - ML_SERVICE_URL=http://ml-service:5001
    depends_on:
      - ml-service
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: finiq-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
