# -*- coding: utf-8 -*-
"""news_fetching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19atXLp9p7Cg7XJCy2MN_ZZdY_BoK6bKG
"""

# Install required library
!pip install requests

import requests
from datetime import datetime, timedelta

# YOUR API KEY HERE (replace with your actual key)
API_KEY = "49fb384f80a2404b8d8107a7030ea317"

# Test function
def fetch_news_test(company_name):
    """
    Simple test to fetch news about a company
    """
    print(f"🔍 Fetching news about {company_name}...\n")

    # Build the URL
    url = "https://newsapi.org/v2/everything"

    # Calculate date range (last 7 days)
    today = datetime.now()
    week_ago = today - timedelta(days=7)

    # Parameters for the request
    params = {
        'q': company_name,           # Search query
        'apiKey': API_KEY,            # Your API key
        'language': 'en',             # English only
        'sortBy': 'publishedAt',      # Newest first
        'pageSize': 10,               # Get 10 articles
        'from': week_ago.strftime('%Y-%m-%d')  # From last week
    }

    # Make the request
    response = requests.get(url, params=params)

    # Check if successful
    if response.status_code == 200:
        data = response.json()
        articles = data.get('articles', [])

        print(f"✅ Found {len(articles)} articles!\n")
        print("=" * 80)

        # Display each article
        for i, article in enumerate(articles, 1):
            print(f"\n{i}. {article['title']}")
            print(f"   Source: {article['source']['name']}")
            print(f"   Published: {article['publishedAt'][:10]}")
            print(f"   URL: {article['url'][:50]}...")
            print("-" * 80)

        return articles
    else:
        print(f"❌ Error: {response.status_code}")
        print(f"Message: {response.json()}")
        return []

# TEST IT!
print("🧪 TESTING NEWS FETCHING")
print("=" * 80)
articles = fetch_news_test("Tesla")

# First, mount Google Drive to access your model||let's combine news fetching WITH your sentiment model!
from google.colab import drive
drive.mount('/content/drive')

# Import model libraries
from transformers import pipeline
import requests
from datetime import datetime, timedelta

# YOUR NEWS API KEY
NEWS_API_KEY = "49fb384f80a2404b8d8107a7030ea317"

# Load your trained model
print("📂 Loading your sentiment model...")
model_path = '/content/drive/MyDrive/FinIQ_Model'

sentiment_analyzer = pipeline(
    "sentiment-analysis",
    model=model_path,
    tokenizer=model_path
)
print("✅ Model loaded!\n")

# Function to fetch news
def fetch_stock_news(company_name, days_back=7):
    """
    Fetch recent news about a company
    """
    print(f"📰 Fetching news about {company_name}...\n")

    url = "https://newsapi.org/v2/everything"

    # Date range
    today = datetime.now()
    past_date = today - timedelta(days=days_back)

    params = {
        'q': company_name,
        'apiKey': NEWS_API_KEY,
        'language': 'en',
        'sortBy': 'publishedAt',
        'pageSize': 10,
        'from': past_date.strftime('%Y-%m-%d')
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        articles = response.json().get('articles', [])
        print(f"✅ Found {len(articles)} articles\n")
        return articles
    else:
        print(f"❌ Error fetching news: {response.status_code}")
        return []

# Function to analyze single headline
def analyze_headline(headline):
    """
    Analyze sentiment of a single headline
    """
    result = sentiment_analyzer(headline)[0]

    # Convert label to readable format
    label = result['label']

    if label == 'LABEL_0' or label == 'negative' or label == 0:
        sentiment = 'NEGATIVE'
        signal = 'SELL'
        emoji = '📉🔴'
    elif label == 'LABEL_2' or label == 'positive' or label == 2:
        sentiment = 'POSITIVE'
        signal = 'BUY'
        emoji = '📈🟢'
    else:
        sentiment = 'NEUTRAL'
        signal = 'HOLD'
        emoji = '➖🟡'

    confidence = result['score'] * 100

    return {
        'sentiment': sentiment,
        'signal': signal,
        'confidence': confidence,
        'emoji': emoji
    }

# Main function - combines everything!
def analyze_stock(company_name):
    """
    Complete analysis: Fetch news + Analyze sentiment
    """
    print("=" * 80)
    print(f"🎯 ANALYZING: {company_name}")
    print("=" * 80)

    # Step 1: Fetch news
    articles = fetch_stock_news(company_name)

    if not articles:
        print("❌ No articles found!")
        return

    # Step 2: Analyze each headline
    print("\n📊 ANALYZING EACH HEADLINE:")
    print("=" * 80)

    results = []

    for i, article in enumerate(articles, 1):
        headline = article['title']

        # Analyze this headline
        analysis = analyze_headline(headline)

        # Store result
        results.append(analysis)

        # Display
        print(f"\n{i}. {headline[:70]}...")
        print(f"   Sentiment: {analysis['sentiment']} {analysis['emoji']}")
        print(f"   Signal: {analysis['signal']}")
        print(f"   Confidence: {analysis['confidence']:.1f}%")
        print("-" * 80)

    # Step 3: Calculate overall signal (coming in Part 4!)
    return results

# TEST THE COMPLETE SYSTEM!
print("\n🚀 COMPLETE SYSTEM TEST")
print("=" * 80)

results = analyze_stock("Tesla")

def calculate_overall_signal(results):
    """
    Combine multiple sentiment results into one overall signal
    """
    print("\n" + "=" * 80)
    print("📈 CALCULATING OVERALL SIGNAL")
    print("=" * 80)

    # Count each sentiment
    positive_count = sum(1 for r in results if r['sentiment'] == 'POSITIVE')
    negative_count = sum(1 for r in results if r['sentiment'] == 'NEGATIVE')
    neutral_count = sum(1 for r in results if r['sentiment'] == 'NEUTRAL')

    # Calculate average confidence
    avg_confidence = sum(r['confidence'] for r in results) / len(results)

    # Display breakdown
    print(f"\n📊 Sentiment Breakdown:")
    print(f"   🟢 Positive: {positive_count} articles")
    print(f"   🔴 Negative: {negative_count} articles")
    print(f"   🟡 Neutral: {neutral_count} articles")
    print(f"   📊 Average Confidence: {avg_confidence:.1f}%")

    # Decision logic
    print(f"\n🤔 Decision Logic:")

    total = len(results)
    positive_ratio = positive_count / total
    negative_ratio = negative_count / total

    print(f"   Positive ratio: {positive_ratio:.1%}")
    print(f"   Negative ratio: {negative_ratio:.1%}")

    # Determine overall signal
    if positive_ratio >= 0.6:  # 60% or more positive
        overall_signal = "STRONG BUY"
        emoji = "🟢🟢"
        explanation = "Majority of news is positive"
    elif positive_ratio >= 0.4:  # 40-60% positive
        overall_signal = "BUY"
        emoji = "🟢"
        explanation = "More positive than negative news"
    elif negative_ratio >= 0.6:  # 60% or more negative
        overall_signal = "STRONG SELL"
        emoji = "🔴🔴"
        explanation = "Majority of news is negative"
    elif negative_ratio >= 0.4:  # 40-60% negative
        overall_signal = "SELL"
        emoji = "🔴"
        explanation = "More negative than positive news"
    else:  # Mixed or mostly neutral
        overall_signal = "HOLD"
        emoji = "🟡"
        explanation = "Mixed or neutral sentiment"

    # Final recommendation
    print(f"\n" + "=" * 80)
    print(f"🎯 FINAL RECOMMENDATION: {overall_signal} {emoji}")
    print(f"=" * 80)
    print(f"💡 Reason: {explanation}")
    print(f"📊 Based on {total} recent articles")
    print(f"🎯 Average confidence: {avg_confidence:.1f}%")
    print("=" * 80)

    return {
        'signal': overall_signal,
        'emoji': emoji,
        'positive_count': positive_count,
        'negative_count': negative_count,
        'neutral_count': neutral_count,
        'avg_confidence': avg_confidence,
        'explanation': explanation
    }

def analyze_stock(company_name):
    """
    Complete analysis with aggregation
    """
    print("=" * 80)
    print(f"🎯 FINIQ ANALYSIS: {company_name.upper()}")
    print("=" * 80)

    # Step 1: Fetch news
    articles = fetch_stock_news(company_name)

    if not articles:
        print("❌ No articles found!")
        return None

    # Step 2: Analyze each headline
    print("\n📊 INDIVIDUAL HEADLINE ANALYSIS:")
    print("=" * 80)

    results = []

    for i, article in enumerate(articles, 1):
        headline = article['title']
        analysis = analyze_headline(headline)
        results.append(analysis)

        print(f"\n{i}. {headline[:65]}...")
        print(f"   {analysis['emoji']} {analysis['sentiment']} → {analysis['signal']} ({analysis['confidence']:.1f}%)")

    # Step 3: Calculate overall signal
    overall = calculate_overall_signal(results)

    return overall

# TEST IT!
print("\n🚀 COMPLETE FINIQ ANALYSIS")
print("\n")

# Try different companies!
analyze_stock("Tesla")

print("\n\n" + "="*80 + "\n\n")

analyze_stock("Apple")